pipeline {
    agent any
    stages {
        stage('Build Frontend') {
            steps {
                dir('frontend'){ 
                   sh "npm install"
                }
            }
        }
        stage('Build Backend') {
            steps {
                dir('frontend'){ 
                   sh "ls -lrt"
                }
            }
        }
        
    }
    post {
        always {
            cleanWs()
        }
    }
}