pipeline {
    agent any
    stages {

       
                stage('Install frontend dependencies') {
                    steps {
                        dir('frontend'){ 
                            echo 'Installing dependencies...'
                            sh """rm -rf node_modules package-lock.json && npm install
                                  npm install -g lighthouse
                            """
                        }
                    }
                }            
                // stage('Build') {
                //     steps {
                //         dir('frontend'){ 
                //             // sh 'npm run build'
                //             echo "Build code"
                //         }
                        
                //     }
                // }
                // stage('Frontend Sonar Code Analysis') {
                //     environment {
                //         scannerHome = tool 'sonar-scanner'
                //         SONAR_TOKEN = "d398500f8060e9da54ca5f802eb0cc5750f1ad13"
                //     }
                //     steps {
                //         dir('frontend'){ 
                //             sh """
                //                ${scannerHome}/bin/sonar-scanner \
                //                 -Dsonar.organization=app-test-demo \
                //                 -Dsonar.projectKey=app-test-proj \
                //                 -Dsonar.sources=. \
                //                 -Dsonar.token="d398500f8060e9da54ca5f802eb0cc5750f1ad13" \
                //                 -Dsonar.host.url=https://sonarcloud.io
                //             """
                //         }
                //     }
                // }
                // stage("Quality Gate"){
                //     steps {
                //         script {
                //             timeout(time: 1, unit: 'HOURS') {
                //                 def qg = waitForQualityGate()
                //                 if (qg.status != 'OK') {
                //                     error "Pipeline aborted due to quality gate failure: ${qg.status}"
                //                 }
                //             }

                //         }
                       
                //     }
                // }
                // stage ('Static Analysis') {
                //     steps {
                //         dir('frontend'){ 
                //             sh """ ./node_modules/eslint/bin/eslint.js -f checkstyle src > eslint.xml
                //                    ls -lrt 
                //             """
                //         }
                        
                //     }
                //     post {
                //         always {
                //             recordIssues enabledForFailure: true, aggregatingResults: true, tool: checkStyle(pattern: 'frontend/eslint.xml')
                //         }
                //     }
                // }
        stage('Install backend dependencies') {
            steps {
                dir('backend'){ 
                   sh "python3 -m pip install -r package-lock.txt"
                }
            }
        }
        // stage('Build backend dependencies') {
        //     steps {
        //         dir('backend'){ 
        //            sh "ppm install"
        //         }
        //     }
        // }

        stage('Deploy app Dev') {
            steps {
                echo "Deploying into Dev Evnironment"
            }
        }

        stage('Run Lighthouse on Dev') {
            steps {
                sh """ lighthouse http://google.com --output html --output-path ./report.html
                       ls -lrt 
                """
            }
        }

        
    }
    post {
        always {
            cleanWs()
        }
    }
}